3 create word model
ProtonPC/jogo-da-forca pull request #7
Opened 2023-09-20 22:44 UTC by alansales00

2023-09-20 23:28 UTC, BdsOliveira requested changes
Algumas pequenas correções serão necessárias.

2023-09-20 23:28 UTC, BdsOliveira commented on src/Models/Word.php
> +    private $name;
Seria interessante adicionar a tipagem dos atributos, nos parâmetros dos métodos da sua classe também.

Se você quiser avançar um pouquinho mais você pode dar uma olhada nesse recurso [Property Promotion](https://www.php.net/releases/8.0/en.php#constructor-property-promotion) lançado no PHP 8, onde você não precisa declarar os atributos na classe, eles são "declarados" dinamicamente ao referencia-los no método construtor.

2023-09-20 23:28 UTC, BdsOliveira commented on src/Models/Word.php
> +    public function Word($name, $level, $tip)
Imagino que a intenção deste método é que ele seja o método construtor. Caso seja, no PHP o construtor de uma classe é chamado através do método mágico "__construct", diferentemente do diagrama de classe que fizemos como referência.

2023-09-20 23:28 UTC, BdsOliveira commented on src/Models/Word.php
> +    public function getName()
Também é interessante adicionar o tipo de retorno dos nossos métodos.

2023-09-20 23:28 UTC, BdsOliveira commented on src/Models/Word.php
> +    public function setName($name){
É obrigatória a instalação do [pre-commit](https://pre-commit.com/) na sua máquina, ele vai lidar com os nossos padrões de codificação.

Como instalar? (comandos devem ser executados no terminal, não no git bash)
- Caso não tenha o Python instalado, ele pode ser baixado [aqui](https://www.python.org/downloads/).
- Com o Python instalado, basta instalar o pip: `py -m ensurepip --upgrade`
- Faça a verificação se a instalação do pip ocorreu bem: `pip --version`
- Caso tudo tenha ocorrido bem, basta instalar o pre-commit: `pip install pre-commit` e depois `pre-commit install`

2023-09-22 15:05 UTC, danieldsf requested changes
Same comments as cite earlier

2023-09-25 21:33 UTC, alansales00 commented on src/Models/Word.php
> +    public function setName($name){
Instalado.

2023-09-25 21:34 UTC, alansales00 commented on src/Models/Word.php
> +    public function getName()
Tipagem adicionada no retorno dos métodos.

2023-09-25 21:35 UTC, alansales00 commented on src/Models/Word.php
> +    public function Word($name, $level, $tip)
Essa era a intenção. Alteração feita.

2023-09-25 21:35 UTC, alansales00 commented on src/Models/Word.php
> +    private $name;
Tipagem dos atributos adicionada.

2023-09-26 00:17 UTC, BdsOliveira approved these changes
Looks good.

2023-09-27 22:52 UTC, BdsOliveira commented
> Same comments as cited earlier

Can we move forward?

2023-09-28 23:43 UTC, danieldsf approved these changes

2023-09-28 23:44 UTC, merged