6 create session controller
ProtonPC/jogo-da-forca pull request #8
Opened 2023-09-21 00:19 UTC by BdsOliveira

2023-09-22 15:03 UTC, danieldsf requested changes
Need some more clarification on where returning null as a string would be beneficial.

2023-09-22 15:03 UTC, danieldsf commented on src/Helpers/Session.php
> +        return self::has($key) ? $_SESSION[$key] : 'null';
Why null as string?

2023-09-22 15:03 UTC, danieldsf commented on src/Helpers/Session.php
> +        return self::has($key) ? $_SESSION[$key] : 'null';
THis can bring ambiguity later

2023-09-25 21:50 UTC, BdsOliveira commented on src/Helpers/Session.php
> +        return self::has($key) ? $_SESSION[$key] : 'null';
FIxed.

2023-09-27 20:12 UTC, danieldsf approved these changes

2023-09-27 22:50 UTC, merged