create user model
ProtonPC/jogo-da-forca pull request #9
Opened 2023-09-21 23:06 UTC by JuniorAires

create user model

2023-09-21 23:29 UTC, BdsOliveira requested changes
Algumas pequenas sugestões para mantermos o nosso padrão de codificação.

2023-09-21 23:29 UTC, BdsOliveira commented on src/Models/User.php
> +use Stringable;
Essa classe não se faz necessária para o nosso contexto.

2023-09-21 23:29 UTC, BdsOliveira commented on src/Models/User.php
> +    public function setRole(String $role)
Neste método faltou o retorno.

2023-09-21 23:29 UTC, BdsOliveira commented on src/Models/User.php
> +    private String $name;
A referência à classe String aparece várias vezes na sua classe, porém podemos substituí-las pelo tipo 'string'.

2023-09-21 23:42 UTC, JuniorAires commented on src/Models/User.php
> +use Stringable;
linha corrigida

2023-09-21 23:42 UTC, JuniorAires commented on src/Models/User.php
> +    public function setRole(String $role)
método alterado

2023-09-21 23:42 UTC, JuniorAires commented on src/Models/User.php
> +    private String $name;
referencias substituídas

2023-09-22 15:01 UTC, danieldsf commented on src/Models/User.php
> +use Stringable;
@BdsOliveira lembrar de resolver a conversa quando a alteracao atingir o criterio desejado

2023-09-22 15:02 UTC, danieldsf requested changes
Same observations as previously cited.

2023-09-28 22:55 UTC, BdsOliveira requested changes
Solve comments previously citted

2023-09-28 23:09 UTC, BdsOliveira approved these changes
Ok

2023-09-28 23:43 UTC, danieldsf approved these changes

2023-09-28 23:44 UTC, merged